// Documentation Commands

const cli = require('pixl-cli');
const Tools = cli.Tools;
const chalk = cli.chalk;
const gray = chalk.gray;

module.exports = {
	
	async cmd_doc() {
		// Fetch one Markdown document, optionally narrowing it to one complete
		// chapter before handing it to the shared terminal renderer.
		var selection = this.consumeDocSelection();
		
		cli.progress.start({ amount: 1, pct: false, text: gray('→ Loading documentation...') });
		var { err, data } = await this.api.getDoc({ doc: selection.doc });
		cli.progress.end();
		if (err) this.die(err);
		if (!data || (typeof(data.text) != 'string')) this.die('Documentation response did not include Markdown text.');
		
		var text = data.text;
		if (selection.chapter) text = this.extractDocChapter(text, selection.doc, selection.chapter);
		text = this.prepareDocMarkdown(text, selection.doc);
		println('\n' + this.markdown(text.trim()).trimEnd());
	},
	
	consumeDocSelection() {
		// Accept either doc/chapter or two positional words.  Keep both portions
		// deliberately strict because the document name maps to a server-side file.
		var values = this.args.other.slice(0);
		delete this.args.other;
		if (Tools.numKeys(this.args)) this.die('Unsupported documentation option: --' + Tools.firstKey(this.args));
		if (values.length > 2) return this.dieUsage('doc');
		
		var doc = values.length ? String(values.shift()) : 'index';
		var chapter = values.length ? String(values.shift()) : '';
		
		if (doc.includes('/')) {
			if (chapter) return this.dieUsage('doc');
			var parts = doc.split('/');
			if ((parts.length != 2) || !parts[0] || !parts[1]) return this.dieUsage('doc');
			doc = parts[0];
			chapter = parts[1];
		}
		
		if (!doc.match(/^\w+$/)) this.die('Invalid documentation name: ' + doc);
		if (doc.toLowerCase() == 'search') this.die('Documentation search is not supported by this command.');
		if (chapter && !chapter.match(/^[a-z0-9_-]+$/i)) this.die('Invalid documentation chapter slug: ' + chapter);
		
		return { doc: doc.toLowerCase(), chapter: chapter.toLowerCase() };
	},
	
	extractDocChapter(text, doc, chapter) {
		// Include the selected heading and all of its descendants, stopping only
		// when the next heading is at the same or a higher document level.
		var lines = String(text).split(/\r?\n/);
		var start = -1;
		var end = lines.length;
		var level = 0;
		var fence = '';
		var slugs = [];
		
		for (var idx = 0; idx < lines.length; idx++) {
			var fence_match = lines[idx].match(/^\s*(`{3,}|~{3,})/);
			if (fence_match) {
				var marker = fence_match[1][0];
				if (!fence) fence = marker;
				else if (fence == marker) fence = '';
				continue;
			}
			if (fence) continue;
			
			var heading = lines[idx].match(/^(#{1,6})[ \t]+(.+?)\s*$/);
			if (!heading) continue;
			var title = heading[2].replace(/\s+#+\s*$/, '').trim();
			var slug = this.getDocHeadingSlug(title);
			slugs.push(slug);
			
			if (start < 0) {
				if (slug != chapter) continue;
				start = idx;
				level = heading[1].length;
			}
			else if (heading[1].length <= level) {
				end = idx;
				break;
			}
		}
		
		if (start < 0) {
			var suggestion = this.findClosestString(chapter, slugs);
			var message = 'Could not find documentation chapter: ' + doc + '/' + chapter + '.';
			if (suggestion) message += ' Did you mean "' + doc + '/' + suggestion + '"?';
			this.die(message);
		}
		
		return lines.slice(start, end).join('\n').trim();
	},
	
	prepareDocMarkdown(text, doc) {
		// Relative documentation links have no useful destination in a terminal.
		// Present them as equivalent CLI commands while preserving web links and
		// leaving example source code completely untouched.
		var fence = '';
		return String(text).split(/\r?\n/).map( function(line) {
			var fence_match = line.match(/^\s*(`{3,}|~{3,})/);
			if (fence_match) {
				var marker = fence_match[1][0];
				if (!fence) fence = marker;
				else if (fence == marker) fence = '';
				return line;
			}
			if (fence) return line;
			
			return line.replace(/\[([^\]\n]+)\]\(([^)\s]+)\)/g, function(all, label, target, offset, source) {
				if (source[offset - 1] == '!') return all;
				var match = target.match(/^(?:(\w+)\.md)?(?:#([a-z0-9_-]+))?$/i);
				if (!match || (!match[1] && !match[2])) return all;
				var target_doc = (match[1] || doc).toLowerCase();
				var command = 'xy doc ' + target_doc + (match[2] ? '/' + match[2].toLowerCase() : '');
				return label + ' (`' + command + '`)';
			});
		}).join('\n');
	},
	
	getDocHeadingSlug(title) {
		// Match the anchor IDs generated by the xyOps documentation page.
		return String(title).trim().replace(/\W+/g, '-').toLowerCase();
	}
	
}; // module.exports
